### ISSUE TITLE
Uploads failing since 1.8.0 release

### ISSUE THREAD

**Issue by badams** [scrutinizer-ci/ocular#53]
I've got multiple code coverage reports being uploaded per PR for a project (PHP and JS), this has worked well up until the last few days, where the second report is being rejected now..

In my case the php test suite is finishing first and uploading the coverage report, and then the js test suite will finish a bit later, and results in this error

```Run curl -L https://scrutinizer-ci.com/ocular.phar > ./ocular.phar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

 23 3837k   23  882k    0     0   655k      0  0:00:05  0:00:01  0:00:04  655k
 56 3837k   56 2174k    0     0   934k      0  0:00:04  0:00:02  0:00:02 1317k
 65 3837k   65 2531k    0     0   764k      0  0:00:05  0:00:03  0:00:02  839k
 73 3837k   73 2837k    0     0   660k      0  0:00:05  0:00:04  0:00:01  662k
 79 3837k   79 3058k    0     0   572k      0  0:00:06  0:00:05  0:00:01  544k
 86 3837k   86 3330k    0     0   527k      0  0:00:07  0:00:06  0:00:01  492k
 92 3837k   92 3551k    0     0   486k      0  0:00:07  0:00:07 --:--:--  277k
100 3837k  100 3837k    0     0   459k      0  0:00:08  0:00:08 --:--:--  259k
100 3837k  100 3837k    0     0   459k      0  0:00:08  0:00:08 --:--:--  246k


                                                      
  [Guzzle\Common\Exception\InvalidArgumentException]  
  Invalid handle provided                             
                                                      


code-coverage:upload [--api-url="..."] [--repository="..."] [--revision="..."] [--format="..."] [--parent="..."] coverage-file


Uploading code coverage for repository "g/****/*****" and revision "fe4f0e******7f947befeb3"... 
Error: Process completed with exit code 1.
```

**Comment by schmittjoh** [comment]
Thanks for this report. Are you using PHP 8 for uploading or another PHP version? Also, do you use the phar file or do you use ocular as a dependency in your project?

**Comment by badams** [comment]
Hi @schmittjoh,

afaik we're using PHP 7.4 (whatever defaults with ubuntu 20), but I can confirm.

Heres a copy of the github action we're running that has this issue 

```
name: 'Frontend CI'
on:
  push:
    branches:
      - master
      - develop
      - test
      - stage
  pull_request:

jobs:
  test:
    env:
      SCRUTINIZER_ACCESS_TOKEN: ${{secrets.SCRUTINIZER_ACCESS_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
      - name: Eslint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier
      - name: Jest
        run: npm run jest -- --coverage

      - name: Upload Coverage report
        run: |
          curl -L https://scrutinizer-ci.com/ocular.phar > ./ocular.phar
          php ocular.phar code-coverage:upload --access-token="${SCRUTINIZER_ACCESS_TOKEN}" --format=clover coverage/clover.xml
```
